### ISSUE TITLE
your indexed records for doi:10.1007/s11284-016-1365-8

### ISSUE THREAD

**Issue by jhammock** [globalbioticinteractions/saito2016#1]
Hi!

Thanks for helping to make existing biotic interaction data easier to find and access!

I was just looking at your GloBI indexed record in the interaction browser, https://www.globalbioticinteractions.org/browse/?interactionType=eatenBy&resultType=json&sourceTaxon=Angelica%20decursiva 

and noticed that one of the taxa is identified in the results as "http:treatment.plazi.orgidE0EAEBE76A22DA73F0C7EAFD11DD90CC"  Selecting the string reveals the taxon preview of Papilio machon. (We also got that url as the taxon name in the EOL resource file.) 

The string is related to the url http://treatment.plazi.org/id/E0EAEBE76A22DA73F0C7EAFD11DD90CC , I think, where the species description lives in TreatmentBank. Is this behavior expected?

**Comment by jhpoelen** [comment]
@jhammock thanks for reporting this issue. This appears to be an old issue rearing its head. 

re-opening https://github.com/globalbioticinteractions/globalbioticinteractions/issues/605

Please confirm that the issue you describe is captured in https://github.com/globalbioticinteractions/globalbioticinteractions/issues/605 , and close this issue as a duplicate.
